name: Purge Artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '0 1 * * *'
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

jobs:
  purge-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: c-hive/gha-remove-artifacts@v1
      # https://github.com/c-hive/gha-remove-artifacts
      with:
        age: '2 days'
        skip-recent: 2
